# Generated by Django 4.0.3 on 2022-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_artist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='url_name',
            field=models.CharField(default='django', max_length=50, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
